# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
#samples: samples.tsv
# path or URL to sequencing unit sheet (TSV format, columns: sample, unit, fq1, fq2)
# Units are technical replicates (e.g. lanes, or resequencing of the same biological
# sample).
#units: units.tsv
# the sequencing adapter
#adapter: ACGGATCGATCGATCGATCGAT

ref:
  # the fasta file
  fasta: "/gpfs/project/mawei111/10X_simulations_PotatoTools/Agria_assembly_final_2020_21_08_Chr01Chr02.fasta"
  # gtf file with transcripts
  #annotation: "path/to/annotation.gtf"
